# Generated by Django 4.1.4 on 2023-03-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Complete', 'Complete'), ('In Production', 'In Production')], max_length=200, null=True),
        ),
    ]
